{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.tls }}
{{- range .Values.ingress.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Values.namespace | default "default" }}
spec:
  secretName: {{ .secretName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

