apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aim.fullname" . }}
  labels:
    {{- include "aim.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aim.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: aim
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: aim-storage
          mountPath: /opt/aim
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: aim-storage
        persistentVolumeClaim:
          claimName: {{ include "aim.fullname" . }}-pvc
      {{- end }}


